export const config = {
    GOOGLE_API_KEY: "GOOGLE_API_KEY",
    SEARCH_ENGINE_ID_BROAD: "SEARCH_ENGINE_ID_BROAD",
    SEARCH_ENGINE_ID_SPECIFIC: "SEARCH_ENGINE_ID_SPECIFIC",
    GEMINI_API_KEY: "GEMINI_API_KEY"
}